### ISSUE TITLE
TypeError raised when url starts with numeric digit and contains a null byte

### ISSUE THREAD

**Issue by arthurprevot** [Shopify/pyreferrer#26]
We came across a "url" that makes pyreferrer blow up in the marketing pageview cleaner. It's because of the string containing `\x00` : 
<img width="814" alt="screen shot 2016-04-13 at 9 50 06 pm" src="https://cloud.githubusercontent.com/assets/3277100/14514781/c0576c12-01c1-11e6-9def-d18f7fa5973d.png">

Shouldn't this library handle this kind of case ? @CamDavidsonPilon @snormore @drdee @bani @samtalasila 

PS: You can ignore the fact that the url is just a filename... and one that looks pretty suspicious :)

**Comment by snormore** [comment]
Yea it looks like it's raising this `TypeError` inside `tldextract` only when the string starts with a numeric digit (in the `looks_like_ip` method).

```
>>> Referrer.parse('1foo\x00.jpg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/snormore/Workspace/starscream/.venv/lib/python2.7/site-packages/pyreferrer/referrer.py", line 89, in parse
    domain_info = tldextract.extract(raw_url)
  File "/Users/snormore/Workspace/starscream/.venv/lib/python2.7/site-packages/tldextract/tldextract.py", line 345, in extract
    return TLD_EXTRACTOR(url)
  File "/Users/snormore/Workspace/starscream/.venv/lib/python2.7/site-packages/tldextract/tldextract.py", line 222, in __call__
    if not tld and netloc and looks_like_ip(netloc):
  File "/Users/snormore/Workspace/starscream/.venv/lib/python2.7/site-packages/tldextract/tldextract.py", line 430, in looks_like_ip
    socket.inet_aton(maybe_ip)
TypeError: must be string without null bytes, not str

>>> Referrer.parse('1f\x00.jpg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/snormore/Workspace/starscream/.venv/lib/python2.7/site-packages/pyreferrer/referrer.py", line 89, in parse
    domain_info = tldextract.extract(raw_url)
  File "/Users/snormore/Workspace/starscream/.venv/lib/python2.7/site-packages/tldextract/tldextract.py", line 345, in extract
    return TLD_EXTRACTOR(url)
  File "/Users/snormore/Workspace/starscream/.venv/lib/python2.7/site-packages/tldextract/tldextract.py", line 222, in __call__
    if not tld and netloc and looks_like_ip(netloc):
  File "/Users/snormore/Workspace/starscream/.venv/lib/python2.7/site-packages/tldextract/tldextract.py", line 430, in looks_like_ip
    socket.inet_aton(maybe_ip)
TypeError: must be string without null bytes, not str

>>> Referrer.parse('1\x00.jpg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/snormore/Workspace/starscream/.venv/lib/python2.7/site-packages/pyreferrer/referrer.py", line 89, in parse
    domain_info = tldextract.extract(raw_url)
  File "/Users/snormore/Workspace/starscream/.venv/lib/python2.7/site-packages/tldextract/tldextract.py", line 345, in extract
    return TLD_EXTRACTOR(url)
  File "/Users/snormore/Workspace/starscream/.venv/lib/python2.7/site-packages/tldextract/tldextract.py", line 222, in __call__
    if not tld and netloc and looks_like_ip(netloc):
  File "/Users/snormore/Workspace/starscream/.venv/lib/python2.7/site-packages/tldextract/tldextract.py", line 430, in looks_like_ip
    socket.inet_aton(maybe_ip)
TypeError: must be string without null bytes, not str

>>> Referrer.parse('foo\x00.jpg')
{u'domain': 'jpg', u'query': u'', u'tld': u'', u'url': 'foo\x00.jpg', u'path': 'foo\x00.jpg', u'subdomain': 'foo\x00', u'type': u'invalid', u'google_search_type': u'Not Google Search', u'label': 'Jpg'}

>>> Referrer.parse('f\x00.jpg')
{u'domain': 'jpg', u'query': u'', u'tld': u'', u'url': 'f\x00.jpg', u'path': 'f\x00.jpg', u'subdomain': 'f\x00', u'type': u'invalid', u'google_search_type': u'Not Google Search', u'label': 'Jpg'}
```

Thanks for reporting @arthurprevot. You're right, the package should be resilient to this case, probably by just removing null bytes, are you able to PR a patch+test?

```
>>> Referrer.parse('1\x00.jpg'.replace('\x00', ''))
{u'domain': 'jpg', u'query': u'', u'tld': u'', u'url': '1.jpg', u'path': '1.jpg', u'subdomain': '1', u'type': u'invalid', u'google_search_type': u'Not Google Search', u'label': 'Jpg'}
```

**Comment by arthurprevot** [comment]
Ok, I will do that.
